version: '3.0'  

services:
  nms:
    image: cordite/network-map
    container_name: nms
    ports:
      - "8084:8080"
    environment:
      - NMS_ROOT_CA_FILE_PATH=/opt/cordite/certs/root.jks
    volumes:
      - ./certs:/opt/cordite/certs/
    # depends_on:
    #   - rabbitmq

  # get_keystore:
  #   image: byrnedo/alpine-curl
  #   container_name: get_keystore
  #   command: "--retry 10 --retry-delay 5 --retry-connrefused http://nms:8080/network-map/truststore -o /tmp/network-root-truststore.jks"
  #   volumes:
  #    - ./Notary/certificates:/tmp
  #   depends_on:
  #     - nms

  notary: 
    image: corda/corda-zulu-java1.8-4.4
    container_name: notary 
    ports:
      - "10001:10201"
      - "10200:10200"
      - "2001:2222"
    #command: "config-generator --generic --exit-on-generate"

    environment:
      - MY_LEGAL_NAME="O=Notary,L=London,C=GB"
      - MY_PUBLIC_ADDRESS="notary"
      - NETWORKMAP_URL="http://nms:8080"
      - DOORMAN_URL="http://nms:8080"
      - NETWORK_TRUST_PASSWORD="changeme"     
      - MY_EMAIL_ADDRESS="cordauser@r3.com"
    volumes:
      - ./Notary/node.conf:/etc/corda/node.conf
      #- ./Notary/config:/etc/corda
      - ./Notary/certificates:/opt/corda/certificates
      - ./Notary/persistence:/opt/corda/persistence
      - ./Notary/logs:/opt/corda/logs
      - ./shared/cordapps:/opt/corda/cordapps
    depends_on:
      #- rabbitmq
      - nms
      #- get_keystore


  # banka: 
  #   image: corda/corda-zulu-java1.8-4.4
  #   container_name: banka 
  #   ports:
  #     - "10002:10201"
  #     - "2002:2222"
  #   environment:
  #     - MY_LEGAL_NAME="O=BankA,L=London,C=GB"
  #     - MY_PUBLIC_ADDRESS="banka"
  #     - NETWORKMAP_URL="http://nms:8080"
  #     - DOORMAN_URL="http://nms:8080"
  #     - NETWORK_TRUST_PASSWORD="trustPass"     
  #     - MY_EMAIL_ADDRESS="cordauser@r3.com"
  #   volumes:
  #     - ./BankA/node.conf:/etc/corda/node.conf
  #     - ./BankA/certificates:/opt/corda/certificates
  #     - ./BankA/persistence:/opt/corda/persistence
  #     - ./BankA/logs:/opt/corda/logs
  #     - ./shared/cordapps:/opt/corda/cordapps
  #   depends_on:
  #     #- rabbitmq
  #     - nms

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  # bankb: 
  #   image: corda/corda-zulu-java1.8-4.4
  #   container_name: bankb 
  #   ports:
  #     - "10003:10201"
  #     - "2003:2222"
  #   volumes:
  #     - ./BankB/node.conf:/etc/corda/node.conf
  #     - ./BankB/certificates:/opt/corda/certificates
  #     - ./BankB/persistence:/opt/corda/persistence
  #     - ./BankB/logs:/opt/corda/logs
  #     - ./shared/cordapps:/opt/corda/cordapps
  #     - ./shared/node-infos:/opt/corda/additional-node-infos
  #     - ./shared/network-parameters:/opt/corda/network-parameters 


  # centralbank: 
  #   image: corda/corda-zulu-java1.8-4.4
  #   container_name: centralbank 
  #   ports:
  #     - "10004:10201"
  #     - "2004:2222"
  #   volumes:
  #     - ./CentralBank/node.conf:/etc/corda/node.conf
  #     - ./CentralBank/certificates:/opt/corda/certificates
  #     - ./CentralBank/persistence:/opt/corda/persistence
  #     - ./CentralBank/logs:/opt/corda/logs
  #     - ./shared/cordapps:/opt/corda/cordapps
  #     - ./shared/node-infos:/opt/corda/additional-node-infos
  #     - ./shared/network-parameters:/opt/corda/network-parameters 
